name: fclones-gui
version: git
summary: Efficient interactive duplicate file finder and remover
description: Finds duplicate files and offers many ways to get rid of them
base: core22
confinement: strict
grade: stable

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  fclones-gui:
    plugin: rust
    source: .
    after: [rust-deps]
    build-packages:
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev
    rust-path:
      - fclones-gui

apps:
  fclones-gui:
    extensions: [gnome]
    command: bin/fclones-gui
    common-id: io.github.pkolaczk.Fclones
    desktop: usr/share/applications/io.github.pkolaczk.Fclones.desktop
    plugs:
      - home
      - removable-media

slots:
  fclones-gui:
    interface: dbus
    bus: session
    name: io.github.pkolaczk.Fclones
