version: 2

jobs:
  format:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Version information
          command: |
            rustc --version; cargo --version; rustup --version
      - run:
          name: Install formatter
          command: |
            rustup component add rustfmt
      - run:
          name: Check format
          command: |
            cargo fmt --all -- --check

  check:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Version information
          command: |
            rustc --version; cargo --version; rustup --version
      - run:
          name: Install Clippy
          command: |
            rustup component add clippy
      - run:
          name: Run Clippy
          command: |
            cargo clippy --all -- -D warnings -D rust-2018-idioms

  build-and-test:
    docker:
      - image: cimg/rust:1.65.0
    environment:
      RUSTFLAGS: '-D warnings'
    steps:
      - run:
          name: Install GTK4
          command: |
            sudo apt update
            sudo apt install -y libgtk-4-dev libadwaita-1-dev
      - checkout
      - run:
          name: Calculate dependencies
          command: |
            rustc --version >rust-version
            test -e Cargo.lock || cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-v1-{{ arch }}-{{checksum "rust-version"}}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: |
            cargo build --all
      - run:
          name: Test
          command: |
            export RUST_BACKTRACE=1
            cargo test
      - save_cache:
          key: cargo-cache-v1-{{ arch }}-{{checksum "rust-version"}}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps


workflows:
  version: 2
  all-checks:
    jobs:
      - format
      - check
      - build-and-test
